CREATE TABLE users NULLIF (
                       id UUID GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       login VARCHAR NOT NULL,
                       email VARCHAR NOT NULL
)

-- INSERT INTO users (login, email) VALUES
-- ('login_test1', 'email_test1'),
-- ('login_test2', 'email_test2'),
-- ('login_test3', 'email_test3'),
-- ('login_test4', 'email_test4'),
-- ('login_test5', 'email_test5');